exports.FONTS_SANS = [
  '"Helvetica Neue"',
  '"Proxima Nova"',
  'ui-sans-serif',
  'system-ui',
  '-apple-system',
  'BlinkMacSystemFont',
  'Segoe UI',
  'Roboto',
  '"Noto Sans"',
  '"Helvetica Neue"',
  'Helvetica',
]
/* exports.FONTS_SERIF = [
  '"Source Serif"',
  'ui-serif',
  'Georgia',
  '"Nimbus Roman No9 L"',
  '"Songti SC"',
  '"Noto Serif CJK SC"',
  '"Source Han Serif SC"',
  '"Source Han Serif CN"',
  'STSong',
  '"AR PL New Sung"',
  '"AR PL SungtiL GB"',
  'NSimSun',
  'SimSun',
  '"TW-Sung"',
  '"WenQuanYi Bitmap Song"',
  '"AR PL UMing CN"',
  '"AR PL UMing HK"',
  '"AR PL UMing TW"',
  '"AR PL UMing TW MBE"',
  'PMingLiU',
  'MingLiU',
  'serif'
]
*/
